### ISSUE TITLE
MX Records not pushed to GCP?

### ISSUE THREAD

**Issue by zeroy99** [octodns/octodns-googlecloud#31]
Hi, I am using OctoDNS 0.9.17 and octodns_googlecloud 0.0.3 when checking config with MX record or when using the "--doit" flag I have no issues reported but the MX records do not appear in the Zone on GCP, everything does (CNAME, TXT, A, SRV records)
My syntax in Yaml file - note the '' is because I need those records for the root domain im updating, I also tried with putting in the domain name instead but this tries to append the domain name twice, any ideas?

```
'':
  - type: MX
    values: 
    - exchange: xyz.xyz.com.
      preference: 10
    - exchange: xyz.xyz.com.
      preference: 10
```
